### ISSUE TITLE
Cant distinguish between YouTube vs YT-andea.  Different App name would be  extremely helpful.  

### ISSUE THREAD

**Issue by blackholeearth** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#25]
I asked the question. There. There is solution.

https://github.com/anddea/revanced-patches/issues/710#issuecomment-2213966423

--------

### Application

YouTube

### Feature description

 Need a different icon , or name "YouTubeAnddea" 

![Screenshot_20240708_144637_Open Link With](https://github.com/anddea/revanced-patches/assets/7512105/de8f62e2-c407-4a17-bc05-721e494b791b)

### Motivation

When i use share button, İ cant distinguish which one is Youtube-Anddea 

.

**Comment by blackholeearth** [comment]
Here the repo manager , gave me this.
Can we implement this!!? 

> Actually you can change the YouTube name to RVX or something else on RVX builder or CLI or on Extensive Builder from j-hc or mine. The feature is `Custom Branding Name`.
> 
> This is the JSON file looks like:
> 
> ```
> [ {
>     "patchName": "Custom branding name YouTube",
>     "options" : [ {
>         "key": "AppName",
>         "value": "YouTube RVX"
>     } ]
> } ]
> ```

**Comment by FiorenMas** [comment]
Fixed in commit https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/commit/63a8a121bb6370f0d0f7499e880a06eef9e08d13
This fix have a problem is only apply to RVX added beta version only. Because dev change patch name in dev branch. So I only change code follow dev branch. When dev update to master branch so you can download stable version with new launcher name.
